default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5

development:
  <<: *default
  database: kakera_development
  socket: /tmp/mysql.sock
  username: root
  password: <%= ENV["DB_PASS"] %>

test:
  <<: *default
  database: kakera_test
  socket: /tmp/mysql.sock
  username: root
  password: <%= ENV["DB_PASS"] %>

production:
  <<: *default
  url: <%= ENV["CLEARDB_DATABASE_URL"] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
